apiVersion: v1
kind: Service
metadata:
  name: next-erp-postgres
  namespace: next-erp-dev
spec:
  selector:
    app: next-erp-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
