apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: next-erp-db-secret
  namespace: next-erp-dev

spec:
  type: kv-v2
  mount: secret
  path: next-erp/dev

  vaultAuthRef: next-erp-vault-auth

  refreshAfter: 1h

  destination:
    name: next-erp-db-secret
    create: true
    overwrite: true
    type: Opaque
